# Generated by Django 6.0.2 on 2026-02-10 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('summary_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collecting', 'Collecting Data'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph_event_id', models.CharField(blank=True, max_length=512)),
                ('subject', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('organizer_name', models.CharField(blank=True, max_length=255)),
                ('organizer_email', models.EmailField(blank=True, max_length=254)),
                ('attendees_json', models.JSONField(default=list)),
                ('body_preview', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('is_online_meeting', models.BooleanField(default=False)),
                ('online_meeting_url', models.URLField(blank=True, max_length=2000)),
                ('web_link', models.URLField(blank=True, max_length=2000)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.dailysummary')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='NoteReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notebook_name', models.CharField(blank=True, max_length=500)),
                ('section_name', models.CharField(blank=True, max_length=500)),
                ('page_title', models.CharField(max_length=500)),
                ('page_graph_id', models.CharField(blank=True, max_length=512)),
                ('content_snippet', models.TextField(blank=True)),
                ('web_url', models.URLField(blank=True, max_length=2000)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_references', to='core.dailysummary')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_graph_id', models.CharField(blank=True, max_length=512)),
                ('content_vtt', models.TextField(blank=True)),
                ('content_plain', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='WordDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=2000)),
                ('content_text', models.TextField(blank=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_documents', to='core.dailysummary')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
