# Generated by Django 6.0.2 on 2026-02-10 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=2000)),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('transcript', 'Transcript')], max_length=20)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.IntegerField(default=0)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.dailysummary')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
    ]
